version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: dead-internet-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  dead-internet:
    build: .
    container_name: dead-internet-app
    ports:
      - "8080:8080"
    depends_on:
      ollama:
        condition: service_healthy
    volumes:
      - ./internet.json:/app/internet.json
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434/v1/

volumes:
  ollama_data:
